/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        secondary: "#6b38d4",
        "on-primary-fixed": "#07006c",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container-high": "#dce9ff",
        outline: "#767586",
        "on-tertiary-fixed": "#191c1e",
        "on-tertiary-fixed-variant": "#444749",
        "tertiary-container": "#727577",
        "on-tertiary-container": "#fbfdff",
        "on-secondary-container": "#fffbff",
        "surface-tint": "#494bd6",
        "on-surface-variant": "#464554",
        "on-surface": "#0b1c30",
        surface: "#f8f9ff",
        "error-container": "#ffdad6",
        "surface-dim": "#cbdbf5",
        "on-primary": "#ffffff",
        background: "#f8f9ff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-container": "#6063ee",
        "secondary-fixed-dim": "#d0bcff",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-fixed-variant": "#5516be",
        error: "#ba1a1a",
        "on-background": "#0b1c30",
        "outline-variant": "#c7c4d7",
        "surface-variant": "#d3e4fe",
        "inverse-surface": "#213145",
        "secondary-fixed": "#e9ddff",
        "secondary-container": "#8455ef",
        "on-primary-container": "#fffbff",
        tertiary: "#595c5e",
        "tertiary-fixed-dim": "#c4c7c9",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#e5eeff",
        "surface-container-low": "#eff4ff",
        "tertiary-fixed": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#c0c1ff",
        "on-secondary-fixed": "#23005c",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed-variant": "#2f2ebe",
        primary: "#4648d4",
        "surface-container-highest": "#d3e4fe",
        "primary-fixed": "#e1e0ff",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        base: "4px",
        sm: "16px",
        "container-max": "1280px",
        xl: "64px",
        xs: "8px",
        lg: "40px",
        md: "24px",
      },
      fontFamily: {
        "label-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
